services:
  - type: web
    name: hexlet-chat
    env: node
    buildCommand: npm install && cd frontend && npm install && npm run build
    startCommand: npx start-server -s ./frontend/dist
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    